### ISSUE TITLE
Plugin fails with latest flake8 (5.0.3)

### ISSUE THREAD

**Issue by Synss** [kmaehashi/flake8-force#3]
This plugin fails with the latest flake8 (5.0.3) with the message
```
There was a critical error during execution of Flake8:
plugin code for `flake8-force[flake8_force]` does not match ^[A-Z]{1,3}[0-9]{0,3}$
```

### Repro

* Update to the latest flake8 `pip install -U flake8`
* Update to the latest flake8-force `pip install -U flake8-force`
* Run `flake8`

### Result

flake8 fails with the error message reported above

### Expected

flake8 checks Python as well as Cython files.

### Analysis

https://github.com/PyCQA/flake8/commit/f3443f4 introduced this new check in flake8.

I believe the error is in https://github.com/kmaehashi/flake8-force/blob/main/setup.py#L28 where you would need to change the left-hand side of the assignment to something that matches `^[A-Z]{1,3}[0-9]{0,3}$`, there are examples https://github.com/PyCQA/flake8/blob/main/example-plugin/setup.py#L14-L17 and elsewhere. I am not really sure how to best chose these values, however.

**Comment by bdice** [comment]
Interesting. It looks like a simple fix, but a little unnecessary for this plugin because this plugin doesn't actually issue error codes, it modifies flake8 internal behaviors.

**Comment by kmaehashi** [comment]
Thanks for reporting! I'll make a release soon.

**Comment by Synss** [comment]
I can confirm that the fix works for me as well. Thank you both for the prompt reaction and the fix!
